### PR TITLE
Updating to add `jekyll-seo-tag` plugin, Adding Logo, Favicon, Adding Title: DD&I

### PR DESCRIPTION
**Pull request by cleverington**
## Issue #8 Resolution

Can someone please test this locally?

My Ruby done blew up and I spent half the weekend just trying to fix it.

## Testing

(Should work, even across forks.... I think.... )

(Must have Ruby, Gems, `github-pages`, Jekyll, etc. installed.)

1. git clone https://github.com/drupaldiversity/drupaldiversity.github.io.git ~/sites/drupaldiversity.github.io
1. `git fetch fork add-seo`
2. `git checkout add-seo`
3. `gem update`
4. `jekyll build`
5. `jekyll serve`

### CODE REVIEW

**Comment by drnikko** [comment]
I'm seeing this in the header on my local:



Is that right?

**Comment by drnikko** [comment]
Also, I see that you added the logo (thank you)... where should I be seeing that?

**Comment by cleverington** [comment]
@drnikki Cleaned it up a bit.  Look it over?

I would put it at ready for Merge under initial review.

**Comment by cleverington** [comment]
See comments and recommended alteration from #7 prior to completion.

**Comment by cleverington** [comment]
@drnikki This branch is ready for Merge. SS below:

dd i_updated

**Comment by drnikko** [comment]
@cleverington+++++++++++++

**Pull request merged**
