### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by rubyji**
Fixing formatting problems.

### CODE REVIEW

**Review by cleverington — APPROVED** [review]
Looks good to me.

Sometimes GitHub Pages is wonky on page-load, so we'll want to double-check it, but I say go ahead and merge.

**Comment by rubyji** [comment]
I don't seem to have the authority to merge. What else is required to make this change?

**Comment by rubyji** [comment]
Yay! Thanks, @cleverington.

**Comment by drnikko** [comment]
<3

**Pull request merged**
