### PR TITLE
Adding Newsletter Subscription.

### PR DESCRIPTION
**Pull request by cleverington**
Please review and comment!

Will get deployed unless anyone would like to be FE-Devs!  ^_^

mailchimp

### CODE REVIEW

**Comment by drnikko** [comment]
@cleverington do we need all three fields? That's a mighty big widget.  Do we need a separate page for that?  haha I'm sorry.  I'm just surprised at it's... size.

**Comment by cleverington** [comment]
@drnikki That's the default from MailChimp, but you tell me preferences?  (I do UI/UX by direction, not by default =>^-^<= )

I can theme it up to have first-name / last-name appear on the same line?

Depending on how much the code provided supports changes, I could even considerably try something along these lines this evening:

mockup

**Comment by cleverington** [comment]
Can / Will probably tweak that background color too.....

**Comment by rootwork** [comment]
(Background: Frontender/UI person.)

I think getting the name fields next to each other makes it easier to read and scan, so I'd agree with that.

While I know this is targeted to DC Baltimore, Drupal being a global community it might be worth altering the "first" and "last" descriptions, which as I understand it are particular to the U.S. (and even then not necessarily inclusive for folks who put their family name first). I just checked and drupal.org uses:

First or given name
Last name or surname 

So that's one option.

Otherwise given the small scope of this within the larger project, I think the design is fine. I wonder what accessibility Mailchimp forms have out of the box, but I'm not sure how alterable that would be anyway.

**Comment by drnikko** [comment]
@cleverington if you want to make Ivan's suggestions, you can merge right after. :)
 Thank you again for doing this.

**Pull request merged**
