### PR TITLE
Issue #36 resolution.

### PR DESCRIPTION
**Pull request by cleverington**
form-tweak

### CODE REVIEW

**Comment by justafish** [comment]
Code looks good 👍 

Maybe we could move this above the fold though?

**Comment by sugaroverflow** [comment]
It looks good to me. 

I'd like to run the wording through @drnikki @heyrocker or @catch56

"Please help increase BDSM/Kink inclusiveness in the DD&I Workgroup."

**Comment by drnikko** [comment]
I'm fine with the wording, but I don't have a ton of experience in this area.  Would love to hear from other folks.

**Comment by rubyji** [comment]
Can we use more consistent and clear language like "the Drupal diversity and inclusion group" instead of "DD&I Workgroup"? I think that's what we're calling ourselves now.

**Comment by cleverington** [comment]
@rubyji Its been a while, but any follow-up thoughts on this one?  I'll have time for some development in the next week and figured I'd toss some fixes at the site.

**Comment by cleverington** [comment]
@sugaroverflow @drnikki 

This PR was initially for adding the option for submitting feedback on creating a more inclusive environment for BSDM / Kink communities when it became a concern over the Summer.

Instead, I feel the text should be changed and the link referenced to be the "anything, please provide feedback" form which is now being shared weekly:  http://goo.gl/dUVq2J 

Perhaps the text could be _"Please help us increase our own inclusiveness and awareness. If you have feedback for us about anything, you can share it anonymously here:"_

The button could just remain _"Submit Feedback"_

Unless anyone has any concerns over the change, I could make those changes and close the related issue / this PR instead of migrating the issues to d.o.

Finally, this PR also resolves our current WCAG / AAA failure on some of the text on our site (though my documenting the fact was horrifically non-existent). -> https://github.com/drupaldiversity/administration/issues/76 Likewise, this issue could be resolved instead of migrating it to d.o.

**Comment by drnikko** [comment]
Thanks @cleverington !!! I merged it for the blues, but I think you're on target - we can just do a generic CTA on the site about providing feedback.  If you could/want to add it here that would probably be fastest.

**Pull request merged**
